### ISSUE TITLE
Blessings do not show as equippable and have no stats

### ISSUE THREAD

**Issue by jburleigh1** [osrsbox/osrsbox-db#91]
Hey Thomas,

This one was opened in November last year (and fixed by you):

https://github.com/osrsbox/osrsbox-db/issues/6

Seems it has snuck back in, I'm seeing no item stats on any of the blessings and they're also showing as equippable : false

Ancient Blessing:
https://www.osrsbox.com/osrsbox-db/items-json/20220.json

Jamie

**Comment by osrsbox** [comment]
Thanks for reporting this issue, it really helps to fix these problems! I have identified the cause. In the OSRS cache data, the blessings have a right-click menu option called `Equip` - see below:

```
  "interfaceOptions": [
    null,
    "Equip",
    null,
    null,
    "Drop"
  ],
```

To determine an equipable item, I was only looking in this array for `Weild` and `Wear`. So I will add `Equip` to this, and it should solve the problem. I might wait to resolve this issue until the next game update (tomorrow), then I can fix it when I do the normal database re-generation.

**Comment by osrsbox** [comment]
About to push to close this issue. The following items have been added that are `equipable` and `equipable_bu_player`... and have a new `equipment` property with stats etc. 

```
id: 278	    name: Cattleprod
id: 3689	name: Lyre
id: 3691	name: Enchanted lyre(1)
id: 6125	name: Enchanted lyre(2)
id: 6126	name: Enchanted lyre(3)
id: 6127	name: Enchanted lyre(4)
id: 9729	name: Elemental helmet
id: 9733	name: Mind helmet
id: 11891	name: Saradomin banner
id: 11892	name: Zamorak banner
id: 13079	name: Enchanted lyre(5)
id: 13328	name: Green banner
id: 20220	name: Holy blessing
id: 20223	name: Unholy blessing
id: 20226	name: Peaceful blessing
id: 20229	name: Honourable blessing
id: 20232	name: War blessing
id: 20235	name: Ancient blessing
id: 22941	name: Rada's blessing 1
id: 22943	name: Rada's blessing 2
id: 22945	name: Rada's blessing 3
id: 22947	name: Rada's blessing 4
```

**Comment by osrsbox** [comment]
This comment is for future reference... a list of all item inventory _actions_ that might be useful in the future.

```
None                     84037
Drop                     22114
Wear                     2255
Wield                    1120
Read                     988
Destroy                  866
Check steps              782
Empty                    528
Drink                    510
Open                     339
Check                    313
Eat                      307
Rub                      126
Uncharge                 117
Discard                  78
Fill                     74
Break                    52
Teleport                 51
Remove-one               47
Bury                     40
Dismantle                40
Inspect                  35
Copy to log              26
Look-at                  25
Release                  22
Equip                    22
Clean                    22
Search                   20
Revert                   19
Open-all                 18
Activate                 16
Hold                     16
Locate                   15
Disassemble              14
Features                 14
Unstuff                  13
Medic                    12
Extinguish               12
Play                     11
Loot                     11
Commune                  9
Jalsavrah                9
Jaleustrophos            9
Jaldraocht               9
Play-with                8
Talk-to                  7
Look-in                  7
Info                     7
Talk-To                  7
Pour                     7
Tell-tofu                6
Tell-worms               6
Preach                   6
Remove-rat               6
Load                     6
Tell-red                 5
Tell-green               5
Tell-blue                5
Tell-crackers            5
Extract                  5
Monastery Teleport       5
Study                    5
Feel                     5
Change                   5
Wind                     4
Check tax                4
Ring                     4
Deposit                  4
Ecto Teleport            4
Recharge-prayer          4
Farm Teleport            4
Restore                  4
Stamina Boost            4
Look                     4
Shake                    4
Kill Area                4
Kourend Woodland         4
Walk                     4
Dance                    4
Assemble                 4
Talk-At                  4
Lay                      3
Plant                    3
Untrim                   3
Functions                3
Trim                     3
Combine                  3
Empty Bowl               3
Options                  3
Prepare                  3
Charge                   3
Cast Bloom               3
Guzzle                   3
Remove-lid               3
Play-With                3
Feed                     3
Jump                     3
Bow                      3
Toggle                   3
Unpack                   3
Check totals             2
Bank                     2
Blow                     2
Gem Mine                 2
Take-one                 2
Bank-all                 2
Settings                 2
Check rank               2
Burgh Teleport           2
Activity                 2
Redeem                   2
Convert                  2
Teleports                2
Smell                    2
View                     2
Dig                      2
Recoil settings          2
Partner                  2
Log                      2
Invoke                   2
Divine                   2
Toggle-absorption        2
Mount Karuulm            2
Check kills              2
Listen                   2
Set-up                   2
Count                    2
Scan                     2
Contact                  2
Playback                 2
Release-all              2
Add-ingreds              2
Toggle Effect            2
Toggle Respawn           2
Spellbook                2
Tele to POH              2
Fishing Guild            2
Otto's Grotto            2
Translate                1
Write-Role               1
Clear                    1
Tell-meat                1
Tell-controlled          1
Tell-accurate            1
Tell-aggressive          1
Tell-defensive           1
Open note                1
Check taxes              1
Pray-over                1
Recite-prayer            1
Operate                  1
Impling-jar              1
Butterfly-jar            1
Toggle-view              1
Refund                   1
Spawn Item               1
Spawn NPCs               1
Dissolve                 1
Check completion         1
Unload                   1
Duradel                  1
Energy                   1
Alchemy                  1
Nardah                   1
Kalphite cave            1
Emote                    1
Scramble                 1
Beat                     1
Fry                      1
Pickle                   1
Consume                  1
Chew                     1
Take-grubs               1
Pack                     1
Check charges            1
Rub-together             1
Blow-on                  1
Investigate              1
Mix-cocktail             1
Add or Remove pages      1
Add pages                1
Invigorate               1
Look at                  1
Snow                     1
Chill                    1
Remove default           1
Remove-legs              1
Throw-water              1
Throw-water direction    1
Check-level              1
Roll                     1
Channel                  1
Puff                     1
Take fish                1
Reminisce                1
Empty Tray               1
Easy                     1
Master                   1
Assessment               1
Control                  1
Spectate                 1
Scry                     1
Bloom                    1
Tele                     1
Kill Bot                 1
Empty Tin                1
Lumbridge                1
Moss Giants              1
King Black Dragon        1
Close                    1
Weiss                    1
Troll Stronghold         1
Fletch                   1
Check/Uncharge           1
Take                     1
Fill/Check               1
Empty Dish               1
Toggle-respawn           1
Look through             1
Release All              1
Cast                     1
Interact                 1
Poke                     1
Heal                     1
Loop                     1
Crazy                    1
Ride                     1
Repair                   1
Follow                   1
Check-keys               1
Spin                     1
Build                    1
Slice                    1
Peel                     1
Mash                     1
Bail-with                1
Untangle                 1
Check-charge             1
Display                  1
Question                 1
Chant                    1
Polish                   1
Return                   1
Complete                 1
Swing                    1
Enchant-Vials            1
Cast Spell               1
Separate                 1
Varrock                  1
Grand Exchange           1
Camelot                  1
Seers' Village           1
Watchtower               1
Yanille                  1
Inside                   1
Outside                  1
Dust-hands               1
Launch                   1
Squash                   1
Shape-Earth              1
Shape-Air                1
Shape-Fire               1
Shape-Water              1
Shape-Mind               1
Blackout                 1
Split                    1
```

**Comment by jburleigh1** [comment]
Hey Thomas,

Thanks for that, the individual files are certainly fixed but I'm still not seeing any blessings in the ammo file here:

https://www.osrsbox.com/osrsbox-db/items-json-slot/items-ammo.json

Are the above files still part of the build process?

Thanks!

**Comment by osrsbox** [comment]
@jburleigh1 - The `items-json-slot` should be part of the build process... but I forgot to run the script yesterday. I will update them soon. But it makes me think that the process should be more automated (or a unit test added), so I don't have to keep remembering each step!
